feat:新增表单评分组件
TencentBlueKing/bk-lesscode pull request #794
Opened 2023-02-28 08:35 UTC by 867-Jige

## 变更点(Changes)

- xxxx

## 相关issues (Which issues this PR fixes)

- Fixes #

## 备注(Special notes)

2023-02-28 08:35 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-lesscode?pullRequest=794) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-lesscode?pullRequest=794) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-lesscode?pullRequest=794) it.</sub>

2023-03-01 02:55 UTC, luofann requested changes

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/render-nocode/form/components/form-edit/association-value/relation-rules.vue
> +            change (e) {
没有用到参数`e`

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/render-nocode/form/components/form-edit/default-value.vue
> +
多余的空行

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/render-nocode/form/components/form-edit/default-value.vue
> +
多余的空行

2023-03-01 02:55 UTC, luofann commented on lib/client/src/views/edit-nocode/components/more-actions/data-manage-operate.vue
> +                // console.log(this.pageDetail)
去掉调试语句

2023-03-01 02:55 UTC, luofann commented on lib/client/src/views/edit-nocode/index.vue
> +                    // console.log(pageDetail)
去掉调试语句

2023-03-01 02:55 UTC, luofann commented on lib/client/src/views/project/index.vue
> -                                    </auth-component> -->
上面这些注释的代码，和本次功能无关的不需要删掉。其他开发者保留可能会有原因。

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/flow-form-comp/form/index.vue
> +                            } else {
不需要写`else`了

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/flow-form-comp/form/index.vue
> +                            this.localValue[field.key] = 0
没有找到满足条件的规则时，会把评分的值置为0吗？

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/render-nocode/form/components/form-edit/association-value/relation-rules.vue
> +                    })
评分组件只能引用相同类型变量的值，在上面的if判断语句增加`RATE`就可以了

2023-03-01 02:55 UTC, luofann commented on lib/client/src/components/render-nocode/form/components/form-edit/association-value/relation-rules.vue
> +                    // 评分组件只能选择数字类型的字段
规则条件字段不受类型的影响

2023-03-01 06:52 UTC, 867-Jige commented on lib/client/src/components/flow-form-comp/form/fields/rate.vue
> +                default: '{}'
在lib\client\src\components\flow-form-comp\form\fieldItem.vue文件中的传入值，有可能是‘’
value: {
                type: [String, Number, Boolean, Array],
                default () {
                    return deepClone(FIELDS_TYPES.find(item => item.type === this.field.type)?.default || '')
                }
            },

2023-03-01 11:20 UTC, terlinhe approved these changes

2023-03-01 11:20 UTC, merged